services:
  db:
    image: gvenzl/oracle-xe
    ports:
      - 1521:1521
      # - 5000:500
    container_name: oracle-xe
    restart: unless-stopped
    environment:
      - ORACLE_DATABASE=STAMP
      - ORACLE_PASSWORD=password123.
      - APP_USER=userd
      - APP_USER_PASSWORD=password123.
    volumes:
      - ./data:/u01/app/oracle/oradata/XE
  redis:
    image: redis:alpine3.22
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped
