services:
  db:
    image: gvenzl/oracle-xe:latest-faststart
    ports:
      - 1521:1521
      # - 5000:500
    container_name: oracle-xe
    restart: unless-stopped
    environment:
      - ORACLE_DATABASE=${DB_SID}
      - ORACLE_PASSWORD=${DB_PASSWORD}
      - APP_USER=${DB_USERNAME}
      - APP_USER_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data:/u01/app/oracle/oradata/XE
  redis:
    image: redis:alpine3.22
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped
